language: c
os:
 - linux
install:
 - . .travis/install_42FileChecker.sh
 - make build_dependencies
 - make build_test_dependencies
 - make gnu_ld
script:
 - make
 - make unit-tests
# - bash ~/42FileChecker/42FileChecker.sh --project "ft_printf" --path "$(pwd)/ft_printf" --no-norminette
# - cat ~/42FileChecker/.my*
