TARGETS := \
	convert_a \
	convert_apostrophe_flag_auxilliaries \
	convert_a_stuffers1 \
	convert_a_stuffers2 \
	convert_b \
	convert_big_k \
	convert_big_k_stuffers \
	convert_b_outputters \
	convert_b_stuffers \
	convert_c \
	convert_d \
	convert_d_stuffers \
	convert_e \
	convert_e_outputters \
	convert_e_stuffers1 \
	convert_e_stuffers2 \
	convert_f \
	convert_fp_to_decimal \
	convert_f_stuffers1 \
	convert_f_stuffers2 \
	convert_g \
	convert_g_estuffers1 \
	convert_g_estuffers2 \
	convert_g_fstuffers1 \
	convert_g_fstuffers2 \
	convert_i \
	convert_k \
	convert_n \
	convert_nospecifier \
	convert_o \
	convert_o_stuffers \
	convert_p \
	convert_pct \
	convert_p_stuffers \
	convert_r \
	convert_s \
	convert_s_hashcharstr \
	convert_sign \
	convert_s_wcharstr \
	convert_syllable_auxilliaries \
	convert_u \
	convert_u_stuffers \
	convert_x \
	convert_x_stuffers \
	etypes_get_etype \
	etypes_sizeof_etype \
	ft_printf \
	get_vaarged_floatingpoint \
	get_va_args \
	get_va_args__vaarger_functions1 \
	get_va_args__vaarger_functions2 \
	get_va_args__vaarger_functions3 \
	get_va_args__vaarger_functions4 \
	get_va_args__vaarger_functions5 \
	get_va_args__vaarger_functions6 \
	global_output_state_auxilliaries \
	global_parse_state_auxilliaries \
	output_chunks \
	output_control \
	output_control_filedescriptor \
	output_fp \
	output_generic \
	output_nan_inf \
	output_nil_null \
	output_padding \
	output_percent_chunk \
	output_simple_chunks \
	output_string \
	output_syllables \
	outputter_auxilliaries \
	pad_syllables \
	parse_auxilliaries \
	parse_format_string \
	parse_format_string_percent \
	parse_format_string_percent_char \
	parse_format_string_percent_control \
	parse_format_string_percent_control_filedes \
	parse_format_string_percent_conversion \
	parse_format_string_percent_conversion_fillers1 \
	parse_format_string_percent_conversion_fillers2 \
	parse_format_string_text \
	parse_literal_integer \
	parse_percent_star_arg \
	parse_state_store_integer \
	tscc_to_tsso \
	tstuffer_auxilliaries
