TARGETS := \
	convert_a \
	convert_bigcharsets \
	convert_c \
	convert_d \
	convert_decompose_floating_point \
	convert_e \
	convert_f \
	convert_g \
	convert_i \
	convert_n \
	convert_nospec \
	convert_o \
	convert_p \
	convert_s \
	convert_sign \
	convert_u \
	convert_x \
	free_parse_state_allocations \
	ft_printf \
	get_va_args \
	get_va_args__vaarger_functions1 \
	get_va_args__vaarger_functions2 \
	get_va_args__vaarger_functions3 \
	get_va_args__vaarger_functions4 \
	get_va_args__vaarger_functions5 \
	get_va_args__vaarger_functions6 \
	my_cleanfree \
	my_lstappend \
	my_stupidmath \
	my_valtobuffers \
	my_valtomybuffers \
	output_chunks \
	output_nan_inf \
	output_padding \
	output_pct_chk \
	output_simple_chunks \
	parse_format_string \
	parse_format_string_percent \
	parse_format_string_percent_char \
	parse_format_string_percent_conversion \
	parse_format_string_percent_conversion_fillers1 \
	parse_format_string_percent_conversion_fillers2 \
	parse_format_string_text \
	parse_literal_integer \
	parse_loops \
	parse_percent_star_arg \
	parse_state_store_integer
