TARGETS := \
	convert_a \
	convert_apostrophe_flag_auxilliaries \
	convert_a_stuffers1 \
	convert_a_stuffers2 \
	convert_c \
	convert_d \
	convert_d_stuffers \
	convert_e \
	convert_e_outputters \
	convert_e_stuffers1 \
	convert_e_stuffers2 \
	convert_f \
	convert_fp_to_decimal \
	convert_f_stuffers1 \
	convert_f_stuffers2 \
	convert_g \
	convert_g_estuffers1 \
	convert_g_estuffers2 \
	convert_g_fstuffers1 \
	convert_g_fstuffers2 \
	convert_i \
	convert_n \
	convert_nospecifier \
	convert_o \
	convert_pad_syllables \
	convert_p \
	convert_s \
	convert_sign \
	convert_stuffers_auxilliaries \
	convert_s_wcharstr \
	convert_syllable_auxilliaries \
	convert_tscc_to_syllable \
	convert_u \
	convert_x \
	etypes_get_etype \
	etypes_sizeof_etype \
	floating_point_auxilliaries \
	floating_point_composition \
	floating_point_decomposition \
	ft_printf \
	get_vaarged_floatingpoint \
	get_va_args \
	get_va_args__vaarger_functions1 \
	get_va_args__vaarger_functions2 \
	get_va_args__vaarger_functions3 \
	get_va_args__vaarger_functions4 \
	get_va_args__vaarger_functions5 \
	get_va_args__vaarger_functions6 \
	global_output_state_auxilliaries \
	global_parse_state_auxilliaries \
	my_cleanfree \
	my_lstappend \
	my_stupidmath \
	my_utf8 \
	my_valtobuffers_raw \
	my_valtobuffers_tscc \
	output_chunks \
	output_fp \
	output_generic \
	output_nan_inf \
	output_padding \
	output_percent_chunk \
	output_simple_chunks \
	output_syllables \
	outputter_auxilliaries \
	parse_auxilliaries \
	parse_format_string \
	parse_format_string_percent \
	parse_format_string_percent_char \
	parse_format_string_percent_conversion \
	parse_format_string_percent_conversion_fillers1 \
	parse_format_string_percent_conversion_fillers2 \
	parse_format_string_text \
	parse_literal_integer \
	parse_percent_star_arg \
	parse_state_store_integer
